"""Tool layer — 47 FunctionTools + GlobalToolset for role-based vending."""

from app.tools._toolset import (
    AGENT_ROLE_MAP,
    ALL_TOOL_FUNCTIONS,
    ROLE_PERMISSIONS,
    GlobalToolset,
    resolve_role,
)
from app.tools.code import code_symbols, run_diagnostics
from app.tools.execution import bash_exec, http_request
from app.tools.filesystem import (
    directory_list,
    file_delete,
    file_edit,
    file_glob,
    file_grep,
    file_insert,
    file_move,
    file_multi_edit,
    file_read,
    file_write,
)
from app.tools.git import (
    git_apply,
    git_branch,
    git_commit,
    git_diff,
    git_log,
    git_show,
    git_status,
    git_worktree,
)
from app.tools.management import (
    check_resources,
    create_project,
    delegate_to_pm,
    escalate_to_ceo,
    escalate_to_director,
    get_project_context,
    list_projects,
    manage_dependencies,
    override_pm,
    query_deliverables,
    query_dependency_graph,
    query_project_status,
    reconfigure_stage,
    reorder_deliverables,
    select_ready_batch,
    update_deliverable,
    validate_brief,
)
from app.tools.task import (
    task_create,
    task_query,
    task_update,
    todo_list,
    todo_read,
    todo_write,
)
from app.tools.web import web_fetch, web_search

__all__ = [
    "AGENT_ROLE_MAP",
    "ALL_TOOL_FUNCTIONS",
    "GlobalToolset",
    "ROLE_PERMISSIONS",
    "bash_exec",
    "check_resources",
    "code_symbols",
    "create_project",
    "delegate_to_pm",
    "directory_list",
    "escalate_to_ceo",
    "escalate_to_director",
    "file_delete",
    "file_edit",
    "file_glob",
    "file_grep",
    "file_insert",
    "file_move",
    "file_multi_edit",
    "file_read",
    "file_write",
    "get_project_context",
    "git_apply",
    "git_branch",
    "git_commit",
    "git_diff",
    "git_log",
    "git_show",
    "git_status",
    "git_worktree",
    "http_request",
    "list_projects",
    "manage_dependencies",
    "override_pm",
    "query_deliverables",
    "query_dependency_graph",
    "query_project_status",
    "reconfigure_stage",
    "reorder_deliverables",
    "resolve_role",
    "run_diagnostics",
    "select_ready_batch",
    "task_create",
    "task_query",
    "task_update",
    "todo_list",
    "todo_read",
    "todo_write",
    "update_deliverable",
    "validate_brief",
    "web_fetch",
    "web_search",
]
